---
--- This command retrieves displayable information for the current craft.
--- The two crafts, Beast Training and Enchanting, have a slightly different UI: the latter has a blue progress bar
--- at the top of the window indicating the player's rank while the former does not.
--- Accordingly, this function returns nil when the Beast Training window is open,
--- while all return values should be valid when the Enchanting window is open.
--- Returns fields in following order:
--- [1] name @ The name of the active craft, or nil if the current craft has no displayable name. Also nil if there are no active crafting windows.
--- [2] rank @ The player's current rank for the named craft, if applicable.
--- [3] maxRank @ The maximum rank for the named craft, if applicable.
---@return string|nil, number|nil, number|nil
function GetCraftDisplaySkillLine() end
